### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by kuchta** [oakesja/elm-news#16]
Please add RSS feature

**Comment by oakesja** [comment]
Hey @kuchta thanks for the suggestion. Individual rss feeds for where elm-news gets its data can be found at: 
- https://discourse.elm-lang.org/latest.rss
- https://www.reddit.com/r/elm/new/.rss

This does not include the elm-google groups since they are now more or less read only. This also does not include elm specific hacker news stories because algolia does not support rss feeds. 

For convenience I created an aggregated rss feed through [rssmix](http://www.rssmix.com/) that can be found at http://www.rssmix.com/u/8302218/rss.xml

I hope this helps
